### PR TITLE
[G4] Instrument implementations

### LINKED ISSUE #337: Need implementation of Lute

### PR DESCRIPTION
**Pull request by sydneyhauke**
Fixes all issues for group G4. Fixes #337 #330 #349 #310 #396 #363 #348 #347

### CODE REVIEW

**Comment by wasadigi** [comment]
Nice :-). Just a couple of things before I accept the PR:

- you have extra files (Trumpet, Instrument, etc.)
- you have some files with headers generated by the IDE

Up to you if you want to ask your team mates to do the change, or if you handle the integration yourself. Thanks!

**Comment by wasadigi** [comment]
You probably have not added/commited everything: I only see the header removed from Mandolin.java.

**Comment by wasadigi** [comment]
Sorry to be picky, but the last 2 files still have the headers...

**Comment by sydneyhauke** [comment]
Did not see those, sorry. Next commit to come should be fine (at last).

**Review by wasadigi — APPROVED** [review]
Great work, thanks!

**Pull request merged**
