### PR TITLE
Fb all instruments

### PR DESCRIPTION
**Pull request by yosra-harbaoui**

### CODE REVIEW

**Comment by wasadigi** [comment]
Can you please explain what is the purpose of this PR in the description? Is that the PR for the entire group (which group)?

**Review by wasadigi — CHANGES_REQUESTED** [review]
Great, thanks! Please just one minor request: remove the IDE generated header in Cornet.java.

**Comment by wasadigi** [comment]
And when you open the PR, please indicate the group number in the description (and explain why you opened the PR).

**Comment by benoit-g** [comment]
This contains all implementations of G3

**Comment by wasadigi** [comment]
Thanks!

**Pull request merged**
